# Basic section
home: "/home"
# END #

# Header section
hasHeader: true
# END #

# Contact section
contactUs: { ownerName: "Balogh Zoltán Sándor",supportEmail: "zoltan.balogh@avolantis.net" }
# END #
