exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: wiki-theme

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/zozobalogh0817/zozobalogh0817.github.io"

title: Wiki Theme
description: This theme is based on GitHub's own Primer Jekyll theme for GitHub Pages
